{% macro get_nation_name(column_name) %}
    CASE {{ column_name }}
        WHEN 0 THEN 'ALGERIA'
        WHEN 1 THEN 'ARGENTINA'
        WHEN 2 THEN 'BRAZIL'
        WHEN 3 THEN 'CANADA'
        WHEN 4 THEN 'EGYPT'
        WHEN 5 THEN 'ETHIOPIA'
        WHEN 6 THEN 'FRANCE'
        WHEN 7 THEN 'GERMANY'
        WHEN 8 THEN 'INDIA'
        WHEN 9 THEN 'INDONESIA'
        WHEN 10 THEN 'IRAN'
        WHEN 11 THEN 'IRAQ'
        WHEN 12 THEN 'JAPAN'
        WHEN 13 THEN 'JORDAN'
        WHEN 14 THEN 'KENYA'
        WHEN 15 THEN 'MOROCCO'
        WHEN 16 THEN 'MOZAMBIQUE'
        WHEN 17 THEN 'PERU'
        WHEN 18 THEN 'CHINA'
        WHEN 19 THEN 'ROMANIA'
        WHEN 20 THEN 'SAUDI ARABIA'
        WHEN 21 THEN 'VIETNAM'
        WHEN 22 THEN 'RUSSIA'
        WHEN 23 THEN 'UNITED KINGDOM'
        WHEN 24 THEN 'UNITED STATES'
        ELSE 'UNKNOWN'
    END
{% endmacro %}